### ISSUE TITLE
Correct README to include iterables

### ISSUE THREAD

**Issue by MadaraUchiha** [tc39/proposal-promise-any#18]
The README at least mentions that `Promise.any()` accepts an array of Promises as the only parameter. The other Promise methods accept iterables.

While I don't think that there's anyone out there really using a Promise iterable which is not an array, it's probably a good idea to be consistent. :heart:

**Comment by benjamingr** [comment]
The actual spec mentions that iterables are accepted https://github.com/tc39/proposal-promise-any/blob/master/spec.html#L59 although the intro there doesn't.
