### ISSUE TITLE
PerformPromiseAny should resolve to a single value, not an array of values

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/proposal-promise-any#24]
E.g. `Promise.any([1, 2, 3])` should return a promise that resolves to the value `1`.

However, the current spec text for [`PerformPromiseAny`](https://tc39.es/proposal-promise-any/#sec-performpromiseany) returns a resolved promise (8.d.iv) with an array of values (`valuesArray` in 8.d.iii.2), instead of just the single value.

```
1. If _remainingElementsCount_.[[Value]] is 0, then
  1. Let _valuesArray_ be CreateArrayFromList(_values_).
  1. Perform ? Call(_resultCapability_.[[Resolve]], *undefined*, &laquo; _valuesArray_ &raquo;).
1. Return _resultCapability_.[[Promise]].
```

@chicoxyzzy Is this a bug, or am I misunderstanding?

**Comment by chicoxyzzy** [comment]
Yes, I think this is a bug
